### ISSUE TITLE
Mounts which do not exist cause a crash

### ISSUE THREAD

**Issue by TripleDogDare** [polydawn/repeatr#101]
Escape mounts for files/dirs which do not exist cause a panic.
Needs better error handling.

**Comment by heavenlyhash** [comment]
Bulk issue close.  We're closing in on the cut-over to the "r200" branch, a major version jump and substantial rewrite of core components, and most of this error handling stuff has changed (hopefully for the better!) so much that this issue has just been left in the dust.

If the issue still exists in the new versions, of course please open an issue with any new symptoms :)

(Mount stuff was rather completely rewritten.  If we still have issues in this area, the bug will now be in the https://github.com/polydawn/rio repo, rather than in repeatr, since those features have been broken out!)
