### ISSUE TITLE
Version Mux stream

### ISSUE THREAD

**Issue by kofalt** [polydawn/repeatr#40]
We should probably throw an int out front of the output stream before anything else.

This would facilitate the storage + playback of output streams across any protocol changes.
And in general it makes us less awful people.

**Comment by heavenlyhash** [comment]
There's a byte mentioned somewhere in the cbor spec that's appropriate.  I forget what.  (Equivalent of the typical assumption that `{` means json.)

Probably wouldn't hurt to put a `{"v": 1}` at the front of the stream, too.

**Comment by heavenlyhash** [comment]
Ah, here it is: https://tools.ietf.org/html/rfc7049#section-2.4.5  Self-Describe CBOR with 0xd9d9f7.

**Comment by kofalt** [comment]
Cool. That's just a byte marker for "I am a CBOR stream", yes?

So we'd probably do both that & a `{"v": 1}`, maybe as the first element in the stream array

**Comment by heavenlyhash** [comment]
Closing.  It's issue tracker cleanup day.

This issue is probably also outdated: the serialized mux system has not proven to be as useful as we might've originally hoped; the replay capabilities are essentially unused; and the combined mux has ordering race conditions by the very nature of how filedescriptors work in linux that result in it being unreproducible in most nontrivial cases, thus not great to store... it's possible that the serialize mux feature should be dropped entirely from repeatr core.
